"""add planned_stays

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 13:02:33.445234
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_stays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upfront_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_planned_stays_dates'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_stays')
    # ### end Alembic commands ###
