"""add users and user_id ownership

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 14:07:16.358050

Autogenerated, then edited by hand: autogenerate adds user_id as NOT NULL in one
step, which fails on tables that already have rows. Instead, each column is added
as nullable, existing rows are backfilled to a demo user, and only then is the
column made NOT NULL. Constraints are named so the downgrade can drop them.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OWNED_TABLES = ("income_events", "expenses", "goals", "planned_stays")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # Existing rows need an owner before user_id can be NOT NULL.
    op.execute("INSERT INTO users (name) VALUES ('Demo student')")

    for table in OWNED_TABLES:
        op.add_column(table, sa.Column("user_id", sa.Integer(), nullable=True))
        op.execute(f"UPDATE {table} SET user_id = (SELECT min(id) FROM users)")
        op.alter_column(table, "user_id", nullable=False)
        op.create_index(f"ix_{table}_user_id", table, ["user_id"])
        op.create_foreign_key(
            f"fk_{table}_user_id_users", table, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )


def downgrade() -> None:
    for table in OWNED_TABLES:
        op.drop_constraint(f"fk_{table}_user_id_users", table, type_="foreignkey")
        op.drop_index(f"ix_{table}_user_id", table_name=table)
        op.drop_column(table, "user_id")
    op.drop_table("users")
